[package]
name = "rust-adventure"
version = "0.1.0"
authors = ["Jason George <jasongeorge21@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
